# Generated by Django 3.1.6 on 2021-02-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mark', models.IntegerField()),
                ('grade', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'web_student',
            },
        ),
    ]
