# Generated by Django 3.1.6 on 2021-02-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
