# Generated by Django 3.1.6 on 2021-04-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0004_auto_20210209_1733'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
