# Generated by Django 3.1.6 on 2021-04-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0005_auto_20210402_2053'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='loginapp_member',
        ),
    ]
