# Generated by Django 3.1.6 on 2021-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Age',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=''),
        ),
    ]
