# Generated by Django 3.1.6 on 2021-04-06 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_auto_20210405_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
    ]
